export const FETCH_POSTS_REQUESTED = 'FETCH_POSTS_REQUESTED';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const NEW_VISIT_REQUESTED = 'NEW_VISIT_REQUESTED';
export const NEW_VISIT_SUCCESS = 'NEW_VISIT_SUCCESS';
export const NEW_VISIT_FAILED = 'NEW_VISIT_FAILED';


export const FETCH_VISITED_REQUESTED = 'FETCH_VISITED_REQUESTED';
export const FETCH_VISITED_SUCCESS = 'FETCH_VISITED_SUCCESS';
export const FETCH_VISITED_FAILED = 'FETCH_VISITED_FAILED';

